version: "3"

services:
  app:
    container_name: containerize_app_1
    # your code goes here ...

    #build the image using the Dockerfile at the app directory
    build: ./app
    image: flash:1.1.1 
#    volumes:
#      - "./:/app/src"
    environment:
      - FLASK_APP=src/server.py
#      - wsgi-file= app/src/app.py
    command: flask run --host=0.0.0.0 
#    command: pwd
    networks:
      my-networks:
        aliases:
          - my_app_1
    # Instruct Docker to always restart the service
    restart: always

    # Serving our application to the port 8000
    ports:
      - "8000:5000"

  nginx:
    container_name: containerize_nginx_1
    # your code goes here ...
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - my-networks
    #volumes:
     # - ./default.conf:/etc/nginx/conf.d/default.conf
networks:
  my-networks:

