version: "3"

services:
  app:
    container_name: containerize_app_1
    # your code goes here ...

    #build the image using the Dockerfile at the app directory
    build: ./app
#    image: flash:1.1.1
    volumes:
      - "./:/app"
#    environment:
#      - FLASK_APP=/code/server.py
#    command: flash run --host=0.0.0.0
#    networks:
#      my-networks:
#        aliases:
#          - containerize_app_1
    # Instruct Docker to always restart the service
    restart: always

    # Serving our application to the port 8000
    expose:
      - 8000

  nginx:
    container_name: containerize_nginx_1
    # your code goes here ...
    build: ./nginx
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - app
    #volumes:
     # - ./default.conf:/etc/nginx/conf.d/default.conf
#networks:
#  my-networks:
