# your code goes here ...
FROM python:3

WORKDIR /usr/src/app

# Copy files from the current directory to /usr/src/app
COPY .

# Install dependencies
RUN pip install no-cache-dir -r requirements.txt

